name: timelapse

on:
  push:
    # branches: [ "main" ]
    branches: [ "**" ]
  pull_request:
    # branches: [ "main" ]
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: cat /etc/nix/nix.conf
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: m74
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run `nix build`
      run: nix build -L .
